- name: Run container
  community.docker.docker_container:
    name: http
    image: jeremydp/opshttp:latest
    pull: true
    recreate: true
    networks:
      - name: ops-network
    ports:
      - "80:80"
  vars:
    ansible_python_interpreter: /usr/bin/python3
