version: '3.7'

services:
  database:
    image: jeremydp/mybd:latest
    networks:
      - ops-network
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

  opsapi:
    image: jeremydp/opsapi:latest
    networks:
      - ops-network
    depends_on:
      - database
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}

  httpd:
    image: jeremydp/opshttp:latest
    ports:
      - '80:80'
    networks:
      - ops-network
    depends_on:
      - opsapi

networks:
  ops-network:
    external: true
