version: '3.7'

services:

  database:
      image: jeremydp/mybd:1.0
      networks:
        - ops-network
      env_file: .env
      environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  opsapi:
    image: jeremydp/opsapi:1.0.1
    networks:
      - ops-network
    depends_on:
      - database
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  httpd:
    image: jeremydp/opshttp:1.0.0
    ports:
      - "80:80"
    networks:
      - ops-network
    depends_on:
      - opsapi

networks:
  ops-network:
    external: true


    
