- name: Run container
  community.docker.docker_container:
    name: database
    image: jeremydp/mybd:latest
    pull: true
    recreate: true
    env:
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_DB: "{{POSTGRES_DB}}"
    networks:
      - name: ops-network
    volumes:
      - /var/lib/postgresql/data
  vars:
    ansible_python_interpreter: /usr/bin/python3
