- name: Run container
  community.docker.docker_container:
    name: opsapi
    image: jeremydp/opsapi:latest
    env:
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_DB: "{{POSTGRES_DB}}"
      POSTGRES_HOST: "{{POSTGRES_HOST}}"
    networks:
      - name: ops-network
  vars:
    ansible_python_interpreter: /usr/bin/python3
